### ISSUE TITLE
Feature request:typescript and composition-api

### ISSUE THREAD

**Issue by zknic** [quasarframework/quasar-ui-qscroller#111]
typescript support
composition-api support

**Comment by hawkeye64** [comment]
@zknic Aside from typings, what do you need for composition api support? I am not sure I understand what you are asking.

**Comment by hawkeye64** [comment]
@zknic Typescript definitons added

**Comment by hawkeye64** [comment]
I see my ts definitions didn't make it in like I thought they would. I will investigate.

**Comment by hawkeye64** [comment]
Nevermind, it's all good. They get generated to the "dist" folder which isn't part of Github, but are on the npm
