### ISSUE TITLE
12:00 AM not showing on header

### ISSUE THREAD

**Issue by RoHell** [quasarframework/quasar-ui-qscroller#175]
When setting time to **12:00 AM** the time from the header disappears.
You can check it on the playground: https://quasarframework.github.io/quasar-ui-qscroller/demo
Tested on macOS Big Sur.

**Comment by hawkeye64** [comment]
ah, you mean like this?
![image](https://user-images.githubusercontent.com/10262924/121682856-d6e33480-ca79-11eb-90dc-83f94b0199a4.png)

**Comment by RoHell** [comment]
Yes. It's a bit odd.

**Comment by hawkeye64** [comment]
I agree. It's probably treating 0 as falsy. Probably should be checking for undefined instead. I haven't quite got the time to fix this today. Unless it's really impacting you, it'll be done sometime next week.

**Comment by RoHell** [comment]
That would be great. This bug really makes the difference.

**Comment by hawkeye64** [comment]
@RoHell Please ping me sometime early next week on this. Thanks. :heart:

**Comment by hawkeye64** [comment]
@RoHell The best I can make this work is to have the time displayed as "00:00"
When you pass 0 to `Intl.DateTimeFormat` (in chrome) it sets the hour to 24.
But, then you can select minutes, such that you could have "24:36", which is not a correct time
but, with the "00:00" option, it then becomes "00:36" which makes more sense.

**Comment by hawkeye64** [comment]
Fixed in v1.1.3
