### ISSUE TITLE
q-date-range-scroller: restrict start date to be less than or equal end date

### ISSUE THREAD

**Issue by apple314159** [quasarframework/quasar-ui-qscroller#18]
There needs to be some semantic relationship between the left and right scrollers so that the left is <= to the right. Would also be good to have some limits such that end date is not past the current date for past ranges or the inverse for future bookings.

**Comment by hawkeye64** [comment]
Agreed. This component is currently in a full rewrite.

**Comment by hawkeye64** [comment]
@apple314159 I can tell you right now, the new refactored code has visual indication of when the start date/time is less than end date/time. It also emits 'invalid-range' if object containing the values of both start and end section.
Is this going to work for now (when it's released)?
Eventually, I hope to have some dynamic disabling of values that restrict in various ways (like 5day week, we starts on monday/sunday), etc.
Of course, color is completely configurable:
![image](https://user-images.githubusercontent.com/10262924/67901506-96e16f00-fb2c-11e9-80ab-3a4d621518ea.png)

**Comment by hawkeye64** [comment]
closing this as a new ticket should be created to request this functionality (q-date-time-scroller no longer exists with the new format)
