### ISSUE TITLE
QTimeScroller prop 'min-time' and 'max-time' no affect

### ISSUE THREAD

**Issue by bjbk** [quasarframework/quasar-ui-qscroller#2]
I am probably implementing this wrong.

**ISSUE: Adding min-time or max-time with string has no effect on scroller**
Example (other props left off for brevity)
```html
<q-time-scroller v-model="time" min-time="08:00" max-time="15:30" />
```
Binding them to a data object has the same result:
`:min-time="timeString"`
`timeString: '08:00'`

Example markup for the image shown:
```html
<q-input color="orange-6" filled v-model="time2" label="Enter time" mask="##:##">
            <template v-slot:append>
              <q-icon name="far fa-clock" class="cursor-pointer">
                <q-popup-proxy v-model="showTimeScroller2">
                  <q-time-scroller
                    v-model="time2"
                    :locale="locale"
                    :rounded-borders="roundedBorders"
                    :no-header="false"
                    :no-footer="false"
                    :disable="disable"
                    bar-color="#21ba45"
                    min-time="08:00"
                    max-time="15:30"
                    color="white"
                    background-color="grey-9"
                    inner-color="grey-9"
                    inner-background-color="white"
                    :style="scrollerPopupStyle120"
                    @close="() => { showTimeScroller2 = false }"
                  />
                </q-popup-proxy>
              </q-icon>
            </template>
          </q-input>
```
<img width="311" alt="Screen Shot 2019-05-10 at 8 46 00 PM" src="https://user-images.githubusercontent.com/7434052/57562866-bc9f6f80-7364-11e9-94f8-dea2189743ab.png">

**Comment by hawkeye64** [comment]
Yes, sorry. Not implemented yet. I see I filled it out in the Docs. I'll add TBD on them until it's finished.

**Comment by bjbk** [comment]
No problem!  I was just trying it out.  I forked the repo, if I can contribute even in a small way, I'll send some PR's. Thanks for a great project!

**Comment by hawkeye64** [comment]
having some help would be great, but coordinate with me if you want to make changes. Since I am actively creating this, I may have already added the new functionality or fix already.

**Comment by bjbk** [comment]
Understood!  No hurry on my account.  ;)

**Comment by bjbk** [comment]
@hawkeye64 just checking in to see if this will eventually be implemented.  Cheers!

**Comment by hawkeye64** [comment]
@bjbk I am in the process of rewriting QScroller. Expect some big changes.

**Comment by hawkeye64** [comment]
ok, so the rewrite is done, but there is no longer a min/max time
I will be adding this in a future release

**Comment by hawkeye64** [comment]
closing this as a new ticket should be created to request this functionality
