### ISSUE TITLE
feat: disable validation prop for edge-cases

### ISSUE THREAD

**Issue by brindosch** [quasarframework/quasar-ui-qscroller#25]
Thank you for this great extension! I noticed a corner case with `time-range` where the validation should be disabled.

To enable/disable dark mode i want to provide a timespan. This usually starts at the evening and ends at the morning. But this is invalid.

Thank you
brindosch

**Comment by hawkeye64** [comment]
@brindosch That is a great edge case and valid. Thanks for reporting this! :heart:

**Comment by hawkeye64** [comment]
Added in v1.0.0
