### ISSUE TITLE
Disable state hides content when 'dark' background

### ISSUE THREAD

**Issue by brindosch** [quasarframework/quasar-ui-qscroller#26]
Just seen that at the demo page. If you set disable to true, the `date-range` content disappears. Is for sure the dark<->light color for text which is overwritten by the disable prop

![qscroller-glitch](https://user-images.githubusercontent.com/15967679/69360094-3ad0bd00-0c8a-11ea-901f-eb5d0f651786.PNG)

**Comment by hawkeye64** [comment]
Thanks for bring this to my attention. :heart:

**Comment by hawkeye64** [comment]
Oops, forgot about this. The demo should be fixed now.
