### ISSUE TITLE
Visual adjustments

### ISSUE THREAD

**Issue by brindosch** [quasarframework/quasar-ui-qscroller#27]
Nothing critical, just for the next roundup

`time-range` with disabled 24h-format requires more space at the header
![date-time-space-no-24h-format2](https://user-images.githubusercontent.com/15967679/69362503-e8de6600-0c8e-11ea-8291-3954f7e048e6.PNG)

`date-time` content looks also a little bit squeezed.
![date-time-space-no-24h-format](https://user-images.githubusercontent.com/15967679/69362572-0d3a4280-0c8f-11ea-8815-38d822ce92b4.PNG)

Keep it up
brindosch

**Comment by brindosch** [comment]
I just noticed, that the time-range has AM/PM at the header but date-time not.
This should be probably streamlined across all modes

**Comment by hawkeye64** [comment]
@brindosch Hey, great for finding these. :heart: Except for the last one, these are all issues for the demo code. If you want, you can PR with new widths on the style to appease that keen eye of yours. :wink:

**Comment by brindosch** [comment]
Can be closed :)
