### ISSUE TITLE
Impossible to set minutes to zero, in "date-time" view.

### ISSUE THREAD

**Issue by paoloar77** [quasarframework/quasar-ui-qscroller#34]
Using date-time view, if before I try to set minutes to '00' (scrolling), after 2 seconds it will change to the actual minute of my PC or mobile phone.

Try the demo:
"Date and Time Selection"
https://quasarframework.github.io/quasar-ui-qscroller/demo

**Comment by hawkeye64** [comment]
@paoloar77 Thanks for reporting, but I am not entirely sure what you mean by "minute machine".

![image](https://user-images.githubusercontent.com/10262924/71671004-ff1c1f00-2d2e-11ea-8490-01858c48f904.png)

**Comment by paoloar77** [comment]
Hi Jeff,
For example:
Now it's 15:16 (in Italy actually).
When I select '00' minutes, suddenly it change automatically to the 16 minutes.

I tried both with chrome and FF
(Linux Ubuntu)

Thanks
Paolo

**Comment by paoloar77** [comment]
I tried now also with my mobile phone (android).
Same issue.

**Comment by hawkeye64** [comment]
ok, I see it now. You have to scroll to '00' very fast or it doesn't cause the issue.
Thanks for reporting. :heart: I will investigate what is going on.

**Comment by hawkeye64** [comment]
Fix will be in v1.0.7. My apologies it took me so long to get this one figured out.
