### ISSUE TITLE
UI of scroller on iOS

### ISSUE THREAD

**Issue by m0jimo** [quasarframework/quasar-ui-qscroller#45]
I use three qscrollers next to each other to simulate a time picker with limited times.

When run it on iPhone with iOS 13.3.1:
- doesn't highlight the active row
- doesn't snap the selected text/value to the center of the field (example with number 6/7)
- when clicked on the number outside the selected row it doesn't change the value
![image](https://user-images.githubusercontent.com/37825539/74346797-627a8180-4db0-11ea-920e-30e858d49106.png)

The same example from Chrome Win 10
![image](https://user-images.githubusercontent.com/37825539/74346823-6e664380-4db0-11ea-85b6-7040718758f2.png)

BTW Thanks for the extension.

**Comment by hawkeye64** [comment]
@m0jimo Uh, this is really hard for me because I don't have access to a mac or iOS. Any chance you can do some digging?

**Comment by hawkeye64** [comment]
Anyone with iOS that can help with this issue, I would really appreciate it. Thanks.

**Comment by filipearena** [comment]
I'm facing the same issue on the Iphone. 
The lib works great on android, but on IOS (safari and chrome) things are different:

- It doesn't center the selected items. 
- The initialized values are not auto-scrolled to. 
- The highlighting of selected items also doesn't work

Not an expert on IOS, but I would guess it was something to do with the way the OS deals with the UI VIEWS (which is very different)

**Comment by zknic** [comment]
i have sovled this issues,
safari and ios add the Line break on innerText of the dom object.
i removed the Line break，safari can render the ui normal.
path:
src>mixins>scroller-base.js
at line no 300
old:
 if (selected.innerText === self.showLabel) {
new:
 if (selected.innerText.replace(/\n|\r/g,"") === self.showLabel) {

![QQ截图20210324173137](https://user-images.githubusercontent.com/11263870/112286934-cdda9680-8cc6-11eb-8c9e-e7a833fa4b33.png)

debug:
<img width="1575" alt="企业微信截图_e35b74b5-7b59-4204-aa50-cebc3d9e1b6a" src="https://user-images.githubusercontent.com/11263870/112287023-e21e9380-8cc6-11eb-9b90-88e677c39e83.png">

**Comment by hawkeye64** [comment]
@zknic Thanks for finding this! :heart: 
Fix will be in v1.1.2
